USE [DB_gesAMM]
GO

/****** Object:  Table [dbo].[HISTORIQUE]    Script Date: 10/12/2021 14:26:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HISTORIQUE](
	[HIS_DATE_UPDATE] [datetime] NOT NULL,
	[HIS_UTILISATEUR] [nvarchar](100) NOT NULL,
	[HIS_ETP_NUM] [int] NOT NULL,
	[HIS_ETP_NORME_AVANT] [nvarchar](20) NOT NULL,
	[HIS_ETP_NORME_APRES] [nvarchar](20) NOT NULL,
	[HIS_ETP_DATE_NORME_AVANT] [date] NOT NULL,
	[HIS_ETP_DATE_NORME_APRES] [date] NOT NULL
) ON [PRIMARY]
GO


